name: Build

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  build:
    name: Build $(git rev-parse --short ${{ github.sha }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build
