name: Test

on:
  workflow_run:
    workflows: [Check]
    types:
      - completed

jobs:
  test:
    name: Test ${{ github.sha }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ["5.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 27017
          mongodb-username: ${{ secrets.MONGODB_USERNAME }}
          mongodb-password: ${{ secrets.MONGODB_PASSWORD }}
          mongodb-db: ${{ secrets.MONGODB_DATABASE }}

      - name: Create .env file
        run: |
          touch .env
          echo MONGODB_TEST_URI=${{ secrets.MONGODB_TEST_URI }} >> .env

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test
