name: Test

on:
  workflow_run:
    workflows: [Check]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ["5.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 27017

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test
